### ISSUE TITLE
Is Nightly required

### ISSUE THREAD

**Issue by dandxy89** [lytefast/gcra-rs#8]
Hello @lytefast 

Would it be possible to create a non-nightly variant of this crate?

```rust
#![feature(div_duration)]
#![feature(is_some_and)]
```

From `src/lib.rs`

**Comment by lytefast** [comment]
No it's not. This is mainly a code readability thing. We can just as easily patch these out. However these features are both stabilized and I'm hoping to just wait for the next release.

https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some_and as of `1.70.0`

https://github.com/rust-lang/rust/issues/63139 - I'm inclined to wait as it looks like it's going to be stabilized soon from comments on all the threads

edit: looks like this is 1.80 https://github.com/rust-lang/rust/blob/master/library/core/src/time.rs#L1115C49-L1115C55

**Comment by lytefast** [comment]
@dandxy89 Looks like 1.80 is going to stabilize`div_duration` on July 25. I'll merge when it hits stable.

**Comment by dandxy89** [comment]
Wow. That's great timing. Appreciate your flexibility.

**Comment by lytefast** [comment]
pushed v0.6.0 with the changes as well.
